"""fill db

Revision ID: 167fc5ad6873
Revises: 
Create Date: 2020-12-13 12:37:22.567568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '167fc5ad6873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'category',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='category_pkey')
    )

    op.create_table(
        'dish',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='dish_category_id_fkey'),
    )

    op.create_table(
        'user',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='user_pkey')
    )

    op.create_table(
        'order',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('dishes', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='order_user_id_fkey'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('dish')
    # ### end Alembic commands ###
